// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQkHVPW1bHgVnsjgv_9r7KQFnawt1V4w',
    appId: '1:1085991503972:web:5e3d1041e20e775b853771',
    messagingSenderId: '1085991503972',
    projectId: 'digi-hack',
    authDomain: 'digi-hack.firebaseapp.com',
    databaseURL: 'https://digi-hack-default-rtdb.firebaseio.com',
    storageBucket: 'digi-hack.appspot.com',
    measurementId: 'G-RT8R91NK7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADw9vuSSHRVR8_LABs3auSR_4TP6w3-ro',
    appId: '1:1085991503972:android:7bde4c055ddb5f52853771',
    messagingSenderId: '1085991503972',
    projectId: 'digi-hack',
    databaseURL: 'https://digi-hack-default-rtdb.firebaseio.com',
    storageBucket: 'digi-hack.appspot.com',
  );
}
